package ke;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.Box;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.UIManager;

class Query extends Panel implements ActionListener {
	Connection con;
	Statement sql;
	ButtonGroup bg;
	JRadioButton male, female;
	JTextField num, name, sex,  year, professional,shangbandaka,xiabandaka,queqin,chuchai1,chuchai2,count1,qingjia1,qingjia2,count2,jiaban1,jiaban2,shijian;
	JButton jb;
	Box box, box0, box1, box2, box4, box5, box6, box7,box8,box9,box10,box11,box12,box13,box14,box15,box16,box17;
	int flag = 0;
	Query() {
		Font font = new Font("华文中宋", Font.BOLD, 10);
		UIManager.put("Label.font", font);
		setLayout(new BorderLayout());
		jb = new JButton("查询");
		jb.setBackground(Color.white);
		jb.setFont(new Font("华文行楷", Font.BOLD, 10));
		jb.setForeground(Color.black);
		jb.addActionListener(this);
		num = new JTextField(26);
		name = new JTextField(20);
		sex = new JTextField(20);
		professional = new JTextField(20);
		year = new JTextField(6);
		shangbandaka = new JTextField(20);
		xiabandaka = new JTextField(20);
		queqin = new JTextField(20);
		chuchai1 = new JTextField(20);
		chuchai2 = new JTextField(20);
		count1 = new JTextField(20);
		qingjia1 = new JTextField(20);
		qingjia2 = new JTextField(20);
		count2 = new JTextField(20);
		jiaban1 = new JTextField(20);
		jiaban2= new JTextField(20);
		shijian = new JTextField(20);
		/* 设置以下属性值不可编辑 */
		name.setEditable(false);
		professional.setEditable(false);
		sex.setEditable(false);
		year.setEditable(false);
		shangbandaka.setEditable(false);
		Panel p1 = new Panel();
		JLabel jl = new JLabel("   查询员工基本信息   ");
		jl.setForeground(Color.red);
		jl.setFont(new Font("华文行楷", Font.BOLD, 10));
		p1.add(jl);
		add(p1, "North");
		box0 = Box.createHorizontalBox();
		box0.add(new JLabel("输入要查询的员工号:"));
		box0.add(Box.createHorizontalStrut(8));
		box0.add(num);
		box0.add(Box.createHorizontalStrut(8));
		box0.add(jb);
		box1 = Box.createHorizontalBox();
		box1.add(new JLabel("姓名:"));
		box1.add(Box.createHorizontalStrut(8));
		box1.add(name);
		box2 = Box.createHorizontalBox();
		box2.add(new JLabel("性别:"));
		box2.add(Box.createHorizontalStrut(8));
		box2.add(sex);
		box4 = Box.createHorizontalBox();
		box4.add(new JLabel("职称:"));
		box4.add(Box.createHorizontalStrut(8));
		box4.add(professional);
		box5 = Box.createHorizontalBox();
		box5.add(new JLabel("年龄:"));
		box5.add(Box.createHorizontalStrut(8));
		box5.add(year);
		box6 = Box.createHorizontalBox();
		box6.add(new JLabel("上班打卡:"));
		box6.add(Box.createHorizontalStrut(8));
		box6.add(shangbandaka);
		box7 = Box.createHorizontalBox();
		box7.add(new JLabel("下班打卡:"));
		box7.add(Box.createHorizontalStrut(8));
		box7.add(xiabandaka);
		box8 = Box.createHorizontalBox();
		box8.add(new JLabel("缺勤:"));
		box8.add(Box.createHorizontalStrut(8));
		box8.add(queqin);
		box9 = Box.createHorizontalBox();
		box9.add(new JLabel("出差开始:"));
		box9.add(Box.createHorizontalStrut(8));
		box9.add(chuchai1);
		box10 = Box.createHorizontalBox();
		box10.add(new JLabel("出差结束:"));
		box10.add(Box.createHorizontalStrut(8));
		box10.add(chuchai2);
		box11 = Box.createHorizontalBox();
		box11.add(new JLabel("出差天数:"));
		box11.add(Box.createHorizontalStrut(8));
		box11.add(count1);
		box12 = Box.createHorizontalBox();
		box12.add(new JLabel("请假开始:"));
		box12.add(Box.createHorizontalStrut(8));
		box12.add(qingjia1);
		box13 = Box.createHorizontalBox();
		box13.add(new JLabel("请假结束:"));
		box13.add(Box.createHorizontalStrut(8));
		box13.add(qingjia2);
		box14 = Box.createHorizontalBox();
		box14.add(new JLabel("请假天数:"));
		box14.add(Box.createHorizontalStrut(8));
		box14.add(count2);
		box15 = Box.createHorizontalBox();
		box15.add(new JLabel("加班开始:"));
		box15.add(Box.createHorizontalStrut(8));
		box15.add(jiaban1);
		box16 = Box.createHorizontalBox();
		box16.add(new JLabel("加班结束:"));
		box16.add(Box.createHorizontalStrut(8));
		box16.add(jiaban2);
		box17 = Box.createHorizontalBox();
		box17.add(new JLabel("加班时间:"));
		box17.add(Box.createHorizontalStrut(8));
		box17.add(shijian);
		box = Box.createVerticalBox();
		box.add(box0);
		box.add(Box.createVerticalStrut(12));
		box.add(box1);
		box.add(Box.createVerticalStrut(12));
		box.add(box2);
		box.add(Box.createVerticalStrut(12));
		box.add(box4);
		box.add(Box.createVerticalStrut(12));
		box.add(box5);
		box.add(Box.createVerticalStrut(12));
		box.add(box6);
		box.add(Box.createVerticalStrut(12));
		box.add(box7);
		box.add(Box.createVerticalStrut(12));
		box.add(box8);
		box.add(Box.createVerticalStrut(12));
		box.add(box9);
		box.add(Box.createVerticalStrut(12));
		box.add(box10);
		box.add(Box.createVerticalStrut(12));
		box.add(box11);
		box.add(Box.createVerticalStrut(12));
		box.add(box12);
		box.add(Box.createVerticalStrut(12));
		box.add(box13);
		box.add(Box.createVerticalStrut(12));
		box.add(box14);
		box.add(Box.createVerticalStrut(12));
		box.add(box15);
		box.add(Box.createVerticalStrut(12));
		box.add(box16);
		box.add(Box.createVerticalStrut(12));
		box.add(box17);
		Panel pCenter = new Panel();
		pCenter.add(box);
		add(pCenter, "Center");
		setSize(300, 250);
		setBackground(Color.yellow);
	}
	public void actionPerformed(ActionEvent e) {
		int flag = 0;
		try {
			Class.forName("com.mysql.jdbc.Driver");
		} catch (ClassNotFoundException ee) {
		}
		try {
			con = DriverManager.getConnection("jdbc:mysql://localhost:3307/Employee", "root", "123456");
			sql = con.createStatement();
			String num1, name1, sex1, year1, professional1, shangbandaka1,xiabandaka1,queqin1,chuchai3,chuchai4,count3,qingjia3,qingjia4,count4,jiaban3,jiaban4,shijian1;
			ResultSet rs = sql.executeQuery("SELECT * FROM stud");
			while (rs.next()) {
				num1 = rs.getString("员工号");
				name1 = rs.getString("姓名");
				sex1 = rs.getString("性别");
				professional1 = rs.getString("职称");
				year1 = rs.getString("年龄");
				shangbandaka1 = rs.getString("上班打卡");
				xiabandaka1 = rs.getString("下班打卡");
				queqin1 = rs.getString("缺勤");
				chuchai3= rs.getString("出差开始");
				chuchai4= rs.getString("出差结束");
				count3 = rs.getString("出差天数");
				qingjia3 = rs.getString("请假开始");
				qingjia4 = rs.getString("请假结束");
				count4= rs.getString("请假天数");
				jiaban3 = rs.getString("加班开始");
				jiaban4= rs.getString("加班结束");
				shijian1= rs.getString("加班时间");
				if (num1.equals(num.getText().trim())) {
					System.out.println("success");
					name.setText(name1);
					sex.setText(sex1);
					year.setText(year1);
					professional.setText(professional1);
					shangbandaka.setText(shangbandaka1);
					xiabandaka.setText(xiabandaka1 );
					queqin.setText(queqin1);
					chuchai1.setText(chuchai3);
					chuchai2.setText(chuchai4);
					count1.setText(count3);
					qingjia1.setText(qingjia3);
					qingjia2.setText(qingjia4);
					count2.setText(count3);
					jiaban1.setText(jiaban3);
					jiaban2.setText(jiaban4);
					shijian.setText(shijian1);
					flag = 1;
					break;
				}
			}
			sql.close();
			con.close();
		} catch (SQLException ex) {
		}
		if (flag == 0) {
			JOptionPane.showMessageDialog(null, "没有该员工相关信息!请重新输入！", "员工管理系统", JOptionPane.ERROR_MESSAGE);
			num.setText(" ");
			name.setText(" ");
			sex.setText("");
			year.setText(" ");
			professional.setText(" ");
			shangbandaka.setText(" ");
			xiabandaka.setText(" ");
			queqin.setText(" ");
			chuchai1.setText(" ");
			chuchai2.setText(" ");
			count1.setText(" ");
			qingjia1.setText(" ");
			qingjia2.setText(" ");
			count2.setText(" ");
			jiaban1.setText(" ");
			jiaban2.setText(" ");
			shijian.setText(" ");
		}
	}
}
